version: '3'
services:
  database-gympass:
    image: bitnami/postgresql
    ports:
      - 5432:5432
    environment:
      - POSTGRESQL_USERNAME=docker
      - POSTGRESQL_PASSWORD=docker
      - POSTGRESQL_DATABASE=bd_gympass
  redis-gympass:
    image: redis
    ports:
      - 6379:6379
