# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  pull_request:
    branches: [master]

jobs:
  deploy:
    runs-on: [ubuntu-latest]

    steps:
      - uses: actions/checkout@v1
      - name: Push to server
        uses: appleboy/ssh-action@v0.1.4
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SERVER_KEY }}
          port: ${{ secrets.SERVER_PORT }}
          passphrase: ${{ secrets.SERVER_PASSPHRASE }}
          script: cd ${{ secrets.PROJECT_PATH }} && git pull && npm run build && pm2 restart server
